In [1]:
import pandas as pd
import time
import matplotlib.pyplot as plt
import seaborn as sn
import numpy as np


from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier

In [3]:
start_time = time.time()
df = pd.read_csv('C:/Users/PC/Desktop/2/pfa/Datasets/Credit Card Fraud Detection/creditcard.csv')
end_time = time.time()

print(f"Temps d'importation : {end_time - start_time} secondes")

Temps d'importation : 3.0046892166137695 secondes

In [4]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
df.shape

(284807, 31)

In [6]:
pd.options.display.float_format = '{:,.9f}'.format

# Print descriptive statistics of the DataFrame
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,"284,807.000000000","284,807.000000000","284,807.000000000","284,807.000000000","284,807.000000000","284,807.000000000","284,807.000000000","284,807.000000000","284,807.000000000","284,807.000000000",...,"284,807.000000000","284,807.000000000","284,807.000000000","284,807.000000000","284,807.000000000","284,807.000000000","284,807.000000000","284,807.000000000","284,807.000000000","284,807.000000000"
mean,"94,813.859575081",0.000000000,0.000000000,-0.000000000,0.000000000,0.000000000,0.000000000,-0.000000000,0.000000000,-0.000000000,...,0.000000000,-0.000000000,0.000000000,0.000000000,0.000000000,0.000000000,-0.000000000,-0.000000000,88.349619251,0.001727486
std,"47,488.145954566",1.958695804,1.651308579,1.516255005,1.415868575,1.380246734,1.332271090,1.237093598,1.194352903,1.098632089,...,0.734524014,0.725701560,0.624460296,0.605647068,0.521278071,0.482227013,0.403632495,0.330083264,250.120109240,0.041527190
min,0.000000000,-56.407509631,-72.715727563,-48.325589362,-5.683171198,-113.743306711,-26.160505936,-43.557241571,-73.216718455,-13.434066318,...,-34.830382145,-10.933143698,-44.807735204,-2.836626919,-10.295397075,-2.604550553,-22.565679321,-15.430083906,0.000000000,0.000000000
25%,"54,201.500000000",-0.920373384,-0.598549913,-0.890364838,-0.848640116,-0.691597071,-0.768295608,-0.554075879,-0.208629744,-0.643097570,...,-0.228394947,-0.542350373,-0.161846345,-0.354586136,-0.317145054,-0.326983926,-0.070839529,-0.052959793,5.600000000,0.000000000
50%,"84,692.000000000",0.018108799,0.065485556,0.179846344,-0.019846529,-0.054335827,-0.274187077,0.040103083,0.022358036,-0.051428732,...,-0.029450168,0.006781943,-0.011192930,0.040976056,0.016593502,-0.052139108,0.001342146,0.011243832,22.000000000,0.000000000
75%,"139,320.500000000",1.315641694,0.803723871,1.027195542,0.743341289,0.611926440,0.398564896,0.570436073,0.327345862,0.597139030,...,0.186377203,0.528553635,0.147642064,0.439526600,0.350715563,0.240952174,0.091045120,0.078279955,77.165000000,0.000000000
max,"172,792.000000000",2.454929991,22.057728990,9.382558433,16.875344034,34.801665877,73.301625546,120.589493945,20.007208365,15.594994607,...,27.202839157,10.503090090,22.528411690,4.584549137,7.519588679,3.517345612,31.612198106,33.847807819,"25,691.160000000",1.000000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB