In [10]:
import pandas as pd
import time
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split

In [11]:
df_train = pd.read_csv('C:/Users/PC/Desktop/2/pfa/Datasets/Credit Card Transactions Fraud Detection Dataset/fraudTrain.csv')

<h1>Jusification a supprimer gneder</h1>

Faible Variance de la Variable : Si la différence entre les taux de fraude par genre est négligeable, la variable gender peut avoir peu ou pas de valeur prédictive. Dans ce cas, vous pourriez envisager de supprimer cette variable, car elle n'apporte pas d'information supplémentaire significative à votre modèle.


Évitement de la Redondance : Si d'autres variables capturent déjà l'essentiel des informations liées à la fraude (par exemple, le montant de la transaction, la localisation, etc.), gender pourrait être redondant.


Prévenir le Biais : Si l'inclusion de la variable gender pourrait introduire un biais non souhaité (par exemple, si le modèle surévalue ou sous-évalue la probabilité de fraude en fonction du genre), vous pourriez également choisir de la supprimer pour des raisons éthiques.

In [12]:
# Compter le nombre de fraudes et de non-fraudes pour chaque genre
fraud_count_by_gender = df_train.groupby(['gender', 'is_fraud']).size().unstack()

# Afficher le résultat
print(fraud_count_by_gender)

is_fraud       0     1
gender
F         706128  3735
M         583041  3771

In [13]:
merchant_counts = df_train['merchant'].value_counts()

# Afficher les résultats
print(merchant_counts)

merchant
fraud_Kilback LLC                       4403
fraud_Cormier LLC                       3649
fraud_Schumm PLC                        3634
fraud_Kuhn LLC                          3510
fraud_Boyer PLC                         3493
                                        ...
fraud_Douglas, DuBuque and McKenzie      775
fraud_Treutel-King                       775
fraud_Medhurst, Labadie and Gottlieb     759
fraud_Reichert-Weissnat                  753
fraud_Hahn, Douglas and Schowalter       727
Name: count, Length: 693, dtype: int64

In [14]:
import pandas as pd

# Grouper par marchand et statut de fraude, puis compter les occurrences
merchant_fraud_counts = df_train.groupby(['merchant', 'is_fraud']).size().unstack(fill_value=0)

# Afficher les résultats
print(merchant_fraud_counts)

is_fraud                             0   1
merchant
fraud_Abbott-Rogahn               1841   3
fraud_Abbott-Steuber              1757   6
fraud_Abernathy and Sons          1747   4
fraud_Abshire PLC                 1886   9
fraud_Adams, Kovacek and Kuhlman   936   4
...                                ...  ..
fraud_Zemlak Group                1280  17
fraud_Zemlak, Tillman and Cremin  1802   2
fraud_Ziemann-Waters              1689   6
fraud_Zieme, Bode and Dooley      2552   8
fraud_Zulauf LLC                  1781   2

[693 rows x 2 columns]

In [15]:
df_train.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [16]:
df_train .dtypes

Unnamed: 0                 int64
trans_date_trans_time     object
cc_num                     int64
merchant                  object
category                  object
amt                      float64
first                     object
last                      object
gender                    object
street                    object
city                      object
state                     object
zip                        int64
lat                      float64
long                     float64
city_pop                   int64
job                       object
dob                       object
trans_num                 object
unix_time                  int64
merch_lat                float64
merch_long               float64
is_fraud                   int64
dtype: object

In [17]:
df_train.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [18]:
from sklearn.feature_selection import VarianceThreshold
import pandas as pd

# Sélectionner uniquement les colonnes numériques
numeric_columns = df_train.select_dtypes(include=['int64', 'float64']).columns

# Créer un nouveau DataFrame avec uniquement les colonnes numériques
X_numeric = df_train[numeric_columns]

# Initialiser VarianceThreshold avec un seuil de variance
selector = VarianceThreshold(threshold=0.1)

# Appliquer la transformation pour supprimer les caractéristiques à faible variance
X_reduced = selector.fit_transform(X_numeric)

# Créer un DataFrame avec les colonnes retenues
X_reduced_df = pd.DataFrame(X_reduced, columns=numeric_columns[selector.get_support()])

# Afficher les colonnes conservées
print("Colonnes retenues après VarianceThreshold :\n", X_reduced_df.columns)

Colonnes retenues après VarianceThreshold :
 Index(['Unnamed: 0', 'cc_num', 'amt', 'zip', 'lat', 'long', 'city_pop',
       'unix_time', 'merch_lat', 'merch_long'],
      dtype='object')

In [9]:

['Unnamed: 0', 'cc_num', 'dob', 'trans_num','first', 'last','street','zip','unix_time','job','gender']

['Unnamed: 0',
 'cc_num',
 'dob',
 'trans_num',
 'first',
 'last',
 'street',
 'zip',
 'unix_time',
 'job',
 'gender']

In [10]:

df_train .drop(columns=['Unnamed: 0', 'cc_num', 'dob', 'trans_num','first', 'last','street','zip','unix_time','job','gender'], inplace= True)
df_train

,trans_date_trans_time,merchant,category,amt,city,state,lat,long,city_pop,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,"fraud_Rippin, Kub and Mann",misc_net,4.97,Moravian Falls,NC,36.0788,-81.1781,3495,36.011293,-82.048315,0
1,2019-01-01 00:00:44,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Orient,WA,48.8878,-118.2105,149,49.159047,-118.186462,0
2,2019-01-01 00:00:51,fraud_Lind-Buckridge,entertainment,220.11,Malad City,ID,42.1808,-112.2620,4154,43.150704,-112.154481,0
3,2019-01-01 00:01:16,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Boulder,MT,46.2306,-112.1138,1939,47.034331,-112.561071,0
4,2019-01-01 00:03:06,fraud_Keeling-Crist,misc_pos,41.96,Doe Hill,VA,38.4207,-79.4629,99,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,2020-06-21 12:12:08,fraud_Reichel Inc,entertainment,15.56,Hatch,UT,37.7175,-112.4777,258,36.841266,-111.690765,0
1296671,2020-06-21 12:12:19,fraud_Abernathy and Sons,food_dining,51.70,Tuscarora,MD,39.2667,-77.5101,100,38.906881,-78.246528,0
1296672,2020-06-21 12:12:32,fraud_Stiedemann Ltd,food_dining,105.93,High Rolls Mountain Park,NM,32.9396,-105.8189,899,33.619513,-105.130529,0
1296673,2020-06-21 12:13:36,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,Manderson,SD,43.3526,-102.5411,1126,42.788940,-103.241160,0
1296674,2020-06-21 12:13:37,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,Sula,MT,45.8433,-113.8748,218,46.565983,-114.186110,0

In [11]:
df_train .dtypes

trans_date_trans_time     object
merchant                  object
category                  object
amt                      float64
city                      object
state                     object
lat                      float64
long                     float64
city_pop                   int64
merch_lat                float64
merch_long               float64
is_fraud                   int64
dtype: object

In [12]:
from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
encoder = LabelEncoder()

# List of columns to encode
columns_to_encode = ['merchant', 'category', 'city', 'state']

# Apply LabelEncoder to each column in the list
for col in columns_to_encode:
    df_train[col] = encoder.fit_transform(df_train[col])

# The rest of your numeric columns should already be in the correct format

In [13]:
df_train ['trans_date_trans_time'] = pd.to_datetime(df_train['trans_date_trans_time'])
df_train ['trans_date_trans_time'] = df_train ['trans_date_trans_time'].apply(lambda x: x.timestamp())

In [14]:
df_train .dtypes

trans_date_trans_time    float64
merchant                   int32
category                   int32
amt                      float64
city                       int32
state                      int32
lat                      float64
long                     float64
city_pop                   int64
merch_lat                float64
merch_long               float64
is_fraud                   int64
dtype: object

In [15]:
X = df_train .drop(columns=['is_fraud'])
Y = df_train ['is_fraud']

In [16]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
scaler = StandardScaler()
X= scaler.fit_transform(X)

In [17]:
X_train, _ , Y_train, _ = train_test_split(X, Y, random_state=42)

In [18]:
X_train_subset, _, Y_train_subset, _ = train_test_split(X, Y, train_size=100000, random_state=42)

In [19]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_balanced, Y_train_balanced = smote.fit_resample(X_train_subset, Y_train_subset)

In [20]:
df_test = pd.read_csv('C:/Users/PC/Desktop/2/pfa/Datasets/Credit Card Transactions Fraud Detection Dataset/fraudTest.csv')

In [21]:
df_test .drop(columns=['Unnamed: 0', 'cc_num', 'dob', 'trans_num','first', 'last','street','zip','unix_time','job','gender'], inplace= True)
df_test

,trans_date_trans_time,merchant,category,amt,city,state,lat,long,city_pop,merch_lat,merch_long,is_fraud
0,2020-06-21 12:14:25,fraud_Kirlin and Sons,personal_care,2.86,Columbia,SC,33.9659,-80.9355,333497,33.986391,-81.200714,0
1,2020-06-21 12:14:33,fraud_Sporer-Keebler,personal_care,29.84,Altonah,UT,40.3207,-110.4360,302,39.450498,-109.960431,0
2,2020-06-21 12:14:53,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Bellmore,NY,40.6729,-73.5365,34496,40.495810,-74.196111,0
3,2020-06-21 12:15:15,fraud_Haley Group,misc_pos,60.05,Titusville,FL,28.5697,-80.8191,54767,28.812398,-80.883061,0
4,2020-06-21 12:15:17,fraud_Johnston-Casper,travel,3.19,Falmouth,MI,44.2529,-85.0170,1126,44.959148,-85.884734,0
...,...,...,...,...,...,...,...,...,...,...,...,...
555714,2020-12-31 23:59:07,fraud_Reilly and Sons,health_fitness,43.77,Luray,MO,40.4931,-91.8912,519,39.946837,-91.333331,0
555715,2020-12-31 23:59:09,fraud_Hoppe-Parisian,kids_pets,111.84,Lake Jackson,TX,29.0393,-95.4401,28739,29.661049,-96.186633,0
555716,2020-12-31 23:59:15,fraud_Rau-Robel,kids_pets,86.88,Burbank,WA,46.1966,-118.9017,3684,46.658340,-119.715054,0
555717,2020-12-31 23:59:24,fraud_Breitenberg LLC,travel,7.99,Mesa,ID,44.6255,-116.4493,129,44.470525,-117.080888,0
555718,2020-12-31 23:59:34,fraud_Dare-Marvin,entertainment,38.13,Edmond,OK,35.6665,-97.4798,116001,36.210097,-97.036372,0

In [22]:
from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
encoder = LabelEncoder()

# List of columns to encode
columns_to_encode = ['merchant', 'category', 'city', 'state']

# Apply LabelEncoder to each column in the list
for col in columns_to_encode:
    df_test[col] = encoder.fit_transform(df_test[col])

# The rest of your numeric columns should already be in the correct format

df_test ['trans_date_trans_time'] = pd.to_datetime(df_test['trans_date_trans_time'])
df_test ['trans_date_trans_time'] = df_test ['trans_date_trans_time'].apply(lambda x: x.timestamp())

In [23]:
df_test.dtypes

trans_date_trans_time    float64
merchant                   int32
category                   int32
amt                      float64
city                       int32
state                      int32
lat                      float64
long                     float64
city_pop                   int64
merch_lat                float64
merch_long               float64
is_fraud                   int64
dtype: object

In [24]:
X_test_initial = df_test .drop(columns=['is_fraud'])
Y_test_initial = df_test ['is_fraud']

In [25]:
scaler = StandardScaler()
X_test_initial= scaler.fit_transform(X_test_initial)

In [26]:
X_test, _ , Y_test, _ = train_test_split(X_test_initial, Y_test_initial, random_state=42)

In [27]:
import time
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Initialiser le modèle SVM avec un noyau linéaire pour une exécution plus rapide
svm_model = SVC(kernel='linear', random_state=42)

# Mesurer le temps d'entraînement
start_time = time.time()

# Entraîner le modèle sur les données d'entraînement
svm_model.fit(X_train_subset, Y_train_subset)

# Calculer le temps d'entraînement
training_time = time.time() - start_time

# Afficher le temps d'entraînement
print(f"Temps d'entraînement du modèle SVM : {training_time:.4f} secondes")

Temps d'entraînement du modèle SVM : 26.0408 secondes

In [28]:
svm_predictions = svm_model.predict(X_test)

# Calculer l'accuracy
svm_accuracy = accuracy_score(Y_test, svm_predictions)

# Afficher l'accuracy
print("SVM Accuracy on Test Data: {:.3f}%".format(svm_accuracy * 100))

SVM Accuracy on Test Data: 99.612%